/*
* generated by Xtext
*/
package soot.jimple.toolkits.transformation.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TransformationLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return soot.jimple.toolkits.transformation.dsl.ui.internal.TransformationLanguageActivator.getInstance().getInjector("soot.jimple.toolkits.transformation.dsl.TransformationLanguage");
	}
	
}
