/*
 * generated by Xtext
 */
package soot.jimple.toolkits.transformation.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TransformationLanguageRuntimeModule extends soot.jimple.toolkits.transformation.dsl.AbstractTransformationLanguageRuntimeModule {

}
