/*
* generated by Xtext
*/
package soot.jimple.toolkits.transformation.dsl.ui.contentassist;

import soot.jimple.toolkits.transformation.dsl.ui.contentassist.AbstractTransformationLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TransformationLanguageProposalProvider extends AbstractTransformationLanguageProposalProvider {

}
