/*
* generated by Xtext
*/
package soot.jimple.toolkits.transformation.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import soot.jimple.toolkits.transformation.dsl.services.TransformationLanguageGrammarAccess;

public class TransformationLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TransformationLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected soot.jimple.toolkits.transformation.dsl.parser.antlr.internal.InternalTransformationLanguageParser createParser(XtextTokenStream stream) {
		return new soot.jimple.toolkits.transformation.dsl.parser.antlr.internal.InternalTransformationLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Transformation";
	}
	
	public TransformationLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TransformationLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
