/*
* generated by Xtext
*/
package soot.jimple.toolkits.transformation.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TransformationLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("soot/jimple/toolkits/transformation/dsl/parser/antlr/internal/InternalTransformationLanguage.tokens");
	}
}
