/*
 * generated by Xtext
 */
package soot.jimple.toolkits.transformation.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import soot.jimple.toolkits.transformation.dsl.ui.internal.TransformationLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TransformationLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TransformationLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TransformationLanguageActivator.getInstance().getInjector(TransformationLanguageActivator.SOOT_JIMPLE_TOOLKITS_TRANSFORMATION_DSL_TRANSFORMATIONLANGUAGE);
	}
	
}
