/*
 * generated by Xtext
 */
package soot.jimple.toolkits.transformation.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TransformationLanguageUiModule extends soot.jimple.toolkits.transformation.dsl.ui.AbstractTransformationLanguageUiModule {
	public TransformationLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
