/*
* generated by Xtext
*/
package soot.jimple.toolkits.transformation.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TransformationLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
